/// Flutter icons HappMeter
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HappMeter
///      fonts:
///       - asset: fonts/HappMeter.ttf
///
/// 
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
///
import 'package:flutter/widgets.dart';

class HappMeter {
  HappMeter._();

  static const _kFontFam = 'HappMeter';

  static const IconData params = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData list = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData trash = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData pencil = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData equalizer = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData list_1 = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData pencil_1 = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData pencil_neg = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData undo = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData trash_empty = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData trash_1 = const IconData(0xe80a, fontFamily: _kFontFam);
}
